const ACTION_TYPES = {
    API_PENDING: 'API_PENDING',
    API_SUCCESS: 'API_SUCCESS',
    API_ERROR: 'API_ERROR',
    TOAST_SUCCESS: 'TOAST_SUCCESS',
    RECOVER_PRODUCT: 'RECOVER_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    CREATE_PRODUCT: 'CREATE_PRODUCT',
    CHANGE_FILTER_ACTIVE: 'CHANGE_FILTER_ACTIVE',
    CHANGE_PAGINATION: 'CHANGE_PAGINATION'
};
export default ACTION_TYPES;